
CREATE TABLE IF NOT EXISTS AWS_CATEGORY_Prime_Video (
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Link VARCHAR(1000) NOT NUll);
CREATE TABLE IF NOT EXISTS AWS_CATEGORY_Amazon_Music (
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Link VARCHAR(1000) NOT NUll);
CREATE TABLE IF NOT EXISTS AWS_CATEGORY_Amazon_Appstore (
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Link VARCHAR(1000) NOT NUll);
CREATE TABLE IF NOT EXISTS AWS_CATEGORY_Amazon_Photos (
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Link VARCHAR(1000) NOT NUll);
CREATE TABLE IF NOT EXISTS AWS_CATEGORY_Echo_AlexaSmart_Home (
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Link VARCHAR(1000) NOT NUll);
CREATE TABLE IF NOT EXISTS AWS_CATEGORY_Fire_TV (
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Link VARCHAR(1000) NOT NUll);
CREATE TABLE IF NOT EXISTS AWS_CATEGORY_Fire_Tablets (
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Link VARCHAR(1000) NOT NUll);
CREATE TABLE IF NOT EXISTS AWS_CATEGORY_Kindle_EreadersEbooks (
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Link VARCHAR(1000) NOT NUll);
CREATE TABLE IF NOT EXISTS AWS_CATEGORY_Books_Audible (
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Link VARCHAR(1000) NOT NUll);
CREATE TABLE IF NOT EXISTS AWS_CATEGORY_Films_TV_MusicGames (
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Link VARCHAR(1000) NOT NUll);
CREATE TABLE IF NOT EXISTS AWS_CATEGORY_Electronics_Computers (
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Link VARCHAR(1000) NOT NUll);
CREATE TABLE IF NOT EXISTS AWS_CATEGORY_Home_Garden_PetsDIY (
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Link VARCHAR(1000) NOT NUll);
CREATE TABLE IF NOT EXISTS AWS_CATEGORY_Beauty_HealthGrocery (
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Link VARCHAR(1000) NOT NUll);
CREATE TABLE IF NOT EXISTS AWS_CATEGORY_Toys_ChildrenBaby (
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Link VARCHAR(1000) NOT NUll);
CREATE TABLE IF NOT EXISTS AWS_CATEGORY_Apparel_ShoesWatches (
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Link VARCHAR(1000) NOT NUll);
CREATE TABLE IF NOT EXISTS AWS_CATEGORY_SportsOutdoors (
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Link VARCHAR(1000) NOT NUll);
CREATE TABLE IF NOT EXISTS AWS_CATEGORY_Automotive_MotorcycleIndustrial (
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Link VARCHAR(1000) NOT NUll);
CREATE TABLE IF NOT EXISTS AWS_CATEGORY_HandmadeAmazon_Launchpad (
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Link VARCHAR(1000) NOT NUll);
CREATE TABLE IF NOT EXISTS AWS_CATEGORY_Amazon_Storefronts (
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Link VARCHAR(1000) NOT NUll);