class Amazon:
    LINK ="LINK"
    TITLE="TITLE"
    SELLER="SELLER"
    SELLER_LINK="SELLER_LINK"
    OFFER_RATING="OFFER_RATING"
    OFFER_TOTAL_RATING="OFFER_TOTAL_RATING"
    OFFER_PRICE="OFFER_PRICE"
    OFFER_PRICE_IS="OFFER_PRICE_IS"
    OFFER_PRICE_WAS="OFFER_PRICE_WAS"
    OFFER_SHIPPING_INFO="OFFER_SHIPPING_INFO"
    OFFER_SHORT_DESCRIPTION="OFFER_SHORT_DESCRIPTION"
    CUSTOMERS_WHO_REVIEWED_TITLE="CUSTOMERS_WHO_REVIEWED_TITLE"
    CUSTOMERS_WHO_REVIEWED_LINK="CUSTOMERS_WHO_REVIEWED_LINK"
    CUSTOMERS_WHO_REVIEWED_IMAGE="CUSTOMERS_WHO_REVIEWED_IMAGE"
    CUSTOMERS_WHO_REVIEWED_STARS="CUSTOMERS_WHO_REVIEWED_STARS"
    CUSTOMERS_WHO_REVIEWED_PRICE="CUSTOMERS_WHO_REVIEWED_PRICE"
    PRODUCT_INFO_TABLE_KEY="PRODUCT_INFO_TABLE_KEY"
    PRODUCT_INFO_TABLE_VALUE="PRODUCT_INFO_TABLE_VALUE"
    PRODUCT_DESCRIPTION="PRODUCT_DESCRIPTION"
    PRODUCT_FROM_MANUFACTURER="PRODUCT_FROM_MANUFACTURER"

    STACK = {
                "QUEUEID":{}, "TITLE":{}, "SELLER":{},"SELLER_LINK":{}, "OFFER_RATING":{},
                "OFFER_TOTAL_RATING":{},"OFFER_PRICE":{}, "OFFER_SHIPPING_INFO":{},
                "OFFER_SHORT_DESCRIPTION":{},"CUSTOMERS_WHO_REVIEWED_TITLE":{},
                "CUSTOMERS_WHO_REVIEWED_LINK":{},"CUSTOMERS_WHO_REVIEWED_IMAGE":{},
                "CUSTOMERS_WHO_REVIEWED_STARS":{},"CUSTOMERS_WHO_REVIEWED_PRICE":{},
                "PRODUCT_INFO_TABLE_KEY":{},"PRODUCT_INFO_TABLE_VALUE":{},
                "PRODUCT_DESCRIPTION":{}, "PRODUCT_FROM_MANUFACTURER":{}
            }

    def Start(self,address):
        pass